# Function File:

#importation du bilio and File :

In [1]:
import numpy as np
import math

Si la taille de la matrice est impaire les ligne et le colonnes des ZEROS doit apparitre dans la resultat
Cette fonction est pour supprimer les zeros et returner la matrice produit que nous voulons

In [32]:
def dlt_Zeros(Matrix, x, y):  # X : La taille de matrice et Y : la taille de matrice apres l'ajoute des zeros
    if x == 3 or x == 5:
        Matrix = Matrix[: y - int(math.log2(y) - 1), : y - int(math.log2(y) - 1)]
    else:
        i = int(math.log2(y) - 1)
        # print(i)
        Matrix = Matrix[
            : (x + 1) - int(math.log2(x + 1) - i),
            : (x + 1) - int(math.log2(x + 1) - i),
        ]
    return Matrix

#Cette fonction est pour deviser les Matrices A et B en sous_matrice de taille N/2 :

In [33]:
def split(Matrix):
    n = len(Matrix)

    return (
        Matrix[: n // 2, : n // 2],
        Matrix[: n // 2, n // 2 :],
        Matrix[n // 2 :, : n // 2],
        Matrix[n // 2 :, n // 2 :],
    )

Test de fonction :

In [34]:
#Ceation du Matrices:
A = np.array(
    [
        [1, 2, 3, 2],
        [0, 4, 6, 2],
        [1, 5, 1, 5],
        [0, 4, 6, 2],
    ]
)


#Afichage du Matices :

In [35]:
print("La Matrice A :\n")
print(A)

La Matrice A :

[[1 2 3 2]
 [0 4 6 2]
 [1 5 1 5]
 [0 4 6 2]]


In [36]:
a,b,c,d = split(A)

print("a = ",a,"\n")
print("b = ",b,"\n")
print("c = ",c,"\n")
print("d = ",d,"\n")

a =  [[1 2]
 [0 4]] 

b =  [[3 2]
 [6 2]] 

c =  [[1 5]
 [0 4]] 

d =  [[1 5]
 [6 2]] 



#Cette fonction est pour ajouter des lignes et colonnes des ZEROS Si la taille de Matrice est impaire

In [37]:
def Add_Zeros(Matrix):
    n = len(Matrix)
    if n % 2 == 0:
        return Matrix
    else:
        B = np.array([np.zeros(n)])
        D = np.array([np.zeros(n + 1)])
        c = np.concatenate((Matrix, B), axis=0)
        c = np.concatenate((c, D.T), axis=1)
        return c

In [38]:
#Test de la fonction :

In [39]:
# Creation de deux Matrices
A = np.array([[2, 3, 4], [6, 7, 8], [13, 14, 15]])
print("size de A : ",A.shape)

size de A :  (3, 3)


#La taille de matrice est impaire Alors en ajoute un ligne et un colonne des ZEROS,
    On appliue la fonction Add_Zeros

In [40]:
M = Add_Zeros(A)
print(M)
print("size de M : ",M.shape)

[[ 2.  3.  4.  0.]
 [ 6.  7.  8.  0.]
 [13. 14. 15.  0.]
 [ 0.  0.  0.  0.]]
size de M :  (4, 4)


# Code main de L'Algorithme

In [41]:
def Strassen(A, B):
    n = len(A)
    k = len(A)
    if n % 2 != 0:
        A = Conv_size(A)
        B = Conv_size(B)
        n = n + 1

    if n <= 2:
        C = np.dot(A, B)
    else:

        A11, A12, A21, A22 = split(A)
        B11, B12, B21, B22 = split(B)

        M1 = Strassen(A11 + A22, B11 + B22)
        M2 = Strassen(A21 + A22, B11)
        M3 = Strassen(A11, B12 - B22)
        M4 = Strassen(A22, B21 - B11)
        M5 = Strassen(A11 + A12, B22)
        M6 = Strassen(A21 - A11, B11 + B12)
        M7 = Strassen(A12 - A22, B21 + B22)

        C11 = M1 + M4 - M5 + M7
        C12 = M3 + M5
        C21 = M2 + M4
        C22 = M1 - M2 + M3 + M6

        C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
        C = dlt_zero(C, k, n)
    return C

# Implimentation de Code Bloc

In [42]:
n = len(A) #prendre la taille du Matrice 
k = len(A) #affecter la tille du Matrice a un autre variable pour eviter la perdu du origin taille

In [43]:
#Cette condtion et pour L'aoujte des Zeros Si la taille du Matrice est impaire
if n % 2 != 0:
    A = Add_Zeros(A)
    B = Add_Zeros(B)
    n = n + 1

In [44]:
#Cette condtion pour calculer Le produit des Matrice de Taille infrieur ou égale à 2
#et aussi c'est la condition d'arréte pour la fonction écursive.
if n <= 2:
    C = np.dot(A, B)

In [45]:
#Le else C-à-d les Matrice de taille supérieur à 2 on appliue la méthode Strassen.
else:

        A11, A12, A21, A22 = split(A)
        B11, B12, B21, B22 = split(B)

        M1 = Strassen(A11 + A22, B11 + B22)
        M2 = Strassen(A21 + A22, B11)
        M3 = Strassen(A11, B12 - B22)
        M4 = Strassen(A22, B21 - B11)
        M5 = Strassen(A11 + A12, B22)
        M6 = Strassen(A21 - A11, B11 + B12)
        M7 = Strassen(A12 - A22, B21 + B22)

        C11 = M1 + M4 - M5 + M7
        C12 = M3 + M5
        C21 = M2 + M4
        C22 = M1 - M2 + M3 + M6

        C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
        C = dlt_zero(C, k, n)

SyntaxError: invalid syntax (<ipython-input-45-41f9952ce691>, line 2)

In [46]:
# 1er Etape : diviser les Matrice
A11, A12, A21, A22 = split(A)
B11, B12, B21, B22 = split(B)

In [47]:
#2ème Etape : Appliquer le combinaision de Strassen avec manière récursive jusu'à la condition d'arrete est vérifier
M1 = Strassen(A11 + A22, B11 + B22)
M2 = Strassen(A21 + A22, B11)
M3 = Strassen(A11, B12 - B22)
M4 = Strassen(A22, B21 - B11)
M5 = Strassen(A11 + A12, B22)
M6 = Strassen(A21 - A11, B11 + B12)
M7 = Strassen(A12 - A22, B21 + B22)

C11 = M1 + M4 - M5 + M7
C12 = M3 + M5
C21 = M2 + M4
C22 = M1 - M2 + M3 + M6

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [48]:
#pour fusionner les C11, C12,C21 et C22 on utilise les fonction prédefini dans numpy avec (hstack et vstack)
#hstack pour la fussione horizontal ET vstack pour la fussion vertical

C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))
# en fussion C11 avec C12 et C21 avec C22 de manière Horizontal
#puis fait la fussion Vertical pour l'ensemble [C11 C12] Et [C21 C22]

NameError: name 'C11' is not defined

In [49]:
#Enfin en supprime les Zeros dans La resultat avec la fonction dlt_Zeros
C = dlt_zero(C, k, n)

In [50]:
#La return du fonction :
return C

SyntaxError: 'return' outside function (<ipython-input-50-1ba25ab699c0>, line 2)

# Fin

©ez7mz