# Test de L'algorithme Strassen

In [6]:
#Importation du biblio et fichier du fonction
from algoFct import *
import numpy as np

Test avec Matrice de taille 7 * 7

Creation de deux Matrices :

In [7]:
#Creation du premier Matrice : 
G = np.array(
    [
        [1, 2, 3, 5, 4, 7, 8],
        [0, 4, 6, 7, 8, 1, 2],
        [1, 5, 1, 7, 7, 5, 4],
        [0, 8, 4, 6, 2, 1, 5],
        [1, 4, 2, 5, 6, 1, 7],
        [0, 0, 4, 1, 7, 5, 4],
        [1, 5, 0, 1, 4, 6, 1],
    ]
)
print("La Matrice A :\n")
print(G)

La Matrice A :

[[1 2 3 5 4 7 8]
 [0 4 6 7 8 1 2]
 [1 5 1 7 7 5 4]
 [0 8 4 6 2 1 5]
 [1 4 2 5 6 1 7]
 [0 0 4 1 7 5 4]
 [1 5 0 1 4 6 1]]


In [8]:
#Creation du deuxieme Matrice :
H = np.array(
    [
        [5, 2, 1, 7, 6, 2, 7],
        [1, 3, 9, 8, 1, 4, 5],
        [9, 3, 4, 5, 2, 4, 1],
        [9, 2, 0, 1, 4, 8, 2],
        [5, 1, 2, 3, 8, 6, 1],
        [2, 0, 3, 5, 9, 6, 4],
        [0, 9, 7, 2, 6, 1, 0],
    ]
)
print("La Matrice B :\n")
print(H)

La Matrice B :

[[5 2 1 7 6 2 7]
 [1 3 9 8 1 4 5]
 [9 3 4 5 2 4 1]
 [9 2 0 1 4 8 2]
 [5 1 2 3 8 6 1]
 [2 0 3 5 9 6 4]
 [0 9 7 2 6 1 0]]


Le produit de A et B avec L'Algorithme de Strassen :

In [9]:
#Le Produit A * B avec Algorithme Strassen :
R = Strassen(G, H)

print("Le Produit A * B avec Algorithme Strassen : \n")
print(R)

Le Produit A * B avec Algorithme Strassen : 

[[113. 103. 116. 106. 177. 136.  62.]
 [163.  70.  93. 102. 129. 152.  52.]
 [127.  77. 107. 113. 166. 158.  74.]
 [110.  95. 130. 111.  95. 119.  62.]
 [104.  99. 109.  91. 133. 115.  49.]
 [ 90.  57.  73.  75. 137. 100.  33.]
 [ 51.  32.  79.  92. 107.  91.  62.]]


In [10]:
#Juste Pour vérification :

print("Le Produit A*B avec Méthode Classique : \n")
print(np.dot(G, H))

Le Produit A*B avec Méthode Classique : 

[[113 103 116 106 177 136  62]
 [163  70  93 102 129 152  52]
 [127  77 107 113 166 158  74]
 [110  95 130 111  95 119  62]
 [104  99 109  91 133 115  49]
 [ 90  57  73  75 137 100  33]
 [ 51  32  79  92 107  91  62]]


©ez7mz

# Fin!